### ISSUE TITLE
User, top-right, dropdown menu, how to disable some items

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#39]
Dears, I want a "non-FindAdmin" User does not see some user's dropdown menu-items, such as "Settings" and "Customization", but I cannot find how to disable them. Is there a way?

**Comment by ciroppina** [comment]
I already tried to remove User from FindAdmin IDOL Role, but without success

**Comment by tung-jin-chew-hp** [comment]
Removing from the FindAdmin IDOL role should work, but it won't take effect till you log out and log in again (if it's the current user).

**Comment by ciroppina** [comment]
Of course I did logout and login again with the removed (from FindAdmin) User; not only, also I restarted Idol Find webapp
But I am not able to see such items to disappear...

**Comment by tung-jin-chew-hp** [comment]
That's odd, what version are you using? I've just tested it with the latest version and it works. How are you removing the user's FindAdmin IDOL role? I used
  http://localhost:9030/action=RoleRemoveUserFromRole&roleName=FindAdmin&username=tungj

Find determines the user by doing a UserRead action when you log in, e.g. http://localhost:9030/Action=UserRead&UserName=tungj&SecurityInfo=true&DeferLogin=true&RoleList=true
which will include the list of roles in the response.

    <autn:role>FindAdmin</autn:role>
    <autn:role>FindUser</autn:role>

If you run a=grl on community, what's the request which is made, and what does the response look like?

**Comment by tung-jin-chew-hp** [comment]
(also, this might sound silly, but is the community server Find is using the same one as the one you're sending commands to? also, are you using the built-in users in community, or roles/grouped obtained from an external source e.g. NT domains or something? if you're using an external source, you might not be able to change the roles via RoleRemoveUserFromRole actions; and I'm wondering if there's any caching involved)

**Comment by ciroppina** [comment]
## Idol Server v 11.6
## Idol Find 11.6.0
## User: burluser

## Sequence of actions:

http://[idolServerHost]:19000/a=RoleGetUserList&RoleName=FindAdmin
##Result:
<response>SUCCESS</response>
<responsedata>
	<autn:totalusers>2</autn:totalusers>
	<autn:numusers>2</autn:numusers>
	<autn:user>Admin</autn:user>
	<autn:user>burluser</autn:user>
</responsedata>

http://[idolServerHost]:19000/a=RoleRemoveUserFromRole&RoleName=FindAdmin&UserName=burluser
##Result:
<action>ROLEREMOVEUSERFROMROLE</action>
<response>SUCCESS</response>

http://[idolServerHost]:19000/a=RoleGetUserList&RoleName=FindAdmin
##Result:
<response>SUCCESS</response>
<responsedata>
	<autn:totalusers>1</autn:totalusers>
	<autn:numusers>1</autn:numusers>
	<autn:user>Admin</autn:user>
</responsedata>

http://[idolServerHost]:19000/a=RoleGetUserList&RoleName=FindUser
##Result:
<response>SUCCESS</response>
<responsedata>
	<autn:totalusers>2</autn:totalusers>
	<autn:numusers>2</autn:numusers>
	<autn:user>Admin</autn:user>
	<autn:user>burluser</autn:user>
</responsedata>

http://[idolServerHost]:19000/a=RoleGetUserList&RoleName=FindBI
##Result:
<response>SUCCESS</response>
<responsedata>
	<autn:totalusers>2</autn:totalusers>
	<autn:numusers>2</autn:numusers>
	<autn:user>Admin</autn:user>
	<autn:user>burluser</autn:user>
</responsedata>

##Windows prompt:
net start "idol 11.6 find" <Enter>
##Result:
Service "idol 11.6 find" start succedeed
PID: 1740

http://localhost:15080/
##Result:
- find login Page: http://localhost:15080/login
Username: burluser
Password: [secret]

##Result:
- find search Page: http://localhost:15080/public/search/query
it still shows the user dropdown menu with: "Settings" and "Customization" items, 
though i translated into italian the [static] root/bundle.js of the core component,
so the two item are displayed as "Impostazioni" and "Personalizzazione"

##from Community GRL
http://[idolServerHost]:19030/Action=UserRead&UserName=burluser&SecurityInfo=true&DeferLogin=true&RoleList=true
##Result:
<response>SUCCESS</response>
<responsedata>
	<autn:numroles>6</autn:numroles>
	<autn:role>FindBI</autn:role>
	<autn:role>FindUser</autn:role>
	<autn:role>burlazio</autn:role>
	<autn:role>everyone</autn:role>
	<autn:role>findadmin</autn:role>
	<autn:role>finduser</autn:role>
	<autn:uid>5</autn:uid>
	<autn:username>burluser</autn:username>
	<autn:locked>false</autn:locked>
	<autn:lockedlasttime>0</autn:lockedlasttime>
	<autn:maxagents>10</autn:maxagents>
	<autn:numagents>0</autn:numagents>
	<autn:emailaddress>c.borrelli@perfexia.it</autn:emailaddress>
	<autn:lastloggedin>1528911054</autn:lastloggedin>
	<autn:numfields>0</autn:numfields>
</responsedata>

##Comment: it looks like "burluser" is listed out-of-the-roles,
  what does it mean ?

**Comment by tung-jin-chew-hp** [comment]
From your a=userread response, it looks like you have another role which is called 'findadmin', all lower case. Try running RoleRemoveUserFromRole on that role as well?

http://[idolServerHost]:19000/a=RoleRemoveUserFromRole&RoleName=findadmin&UserName=burluser

By the way, if you add four spaces before XML when pasting it, it'll be formatted correctly.

**Comment by ciroppina** [comment]
SOLVED, I wrongly dded the User "burluser" to a not-existent lowercase role: 'findadmin'
nonetheless Community considered such a false 'role' (_not listed with action "RoleGetRoleList_"); now correctly Find search Page's user dropdown menu does no longer lists "admininstrative" items
THANKS 4 Ur support
![schermata 2018-06-13 a 20 16 38](https://user-images.githubusercontent.com/15525117/41370310-ce303302-6f36-11e8-94b5-2aee5ee40b33.png)
