### ISSUE TITLE
how-to restrict FIND databases access by User's roles & privileges

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#40]
dear Sirs, I need to restrict databases access, in Find, according to current authenticated user.
I followed this documentation from HPE:
- "[http://h30359.www3.hpe.com/online_help/IDOL/IAS/IAS/11.1/Guides/html/English/admin/Content/IAS/Appendixes/Restrict_Database_Access.htm](http://h30359.www3.hpe.com/online_help/IDOL/IAS/IAS/11.1/Guides/html/English/admin/Content/IAS/Appendixes/Restrict_Database_Access.htm)"

where You can read (_step 4_) that:
"The front-end application can now include the Databases privilege’s values in queries this user sends to IDOL server. To specify databases to which a query is restricted, for example, the front end app should add the **DatabaseMatch** parameter to the query it sends, and set it with the value that the **RoleGetUserPrivilegeValueList** action returned"

Is there a way to configure FIND for getting from Idol the current **RoleGetUserPrivilegeValueList** in order to send queries **ONLY** to the returned list of Databases?

**NOTICE THAT, IN IDOL Server:**
a) I created a new role called "myDatabases";
b) I created a new user "sascuser" and added it to the "myDatabases" role;
c) I created a new privilege "myDatabasesPrivilege" vith a list of `Values=db1,db2,db3,db4`
d) I added such new privilege to "myDatabases" role;
THEN:
e) I modified FIND launching **java** command adding the fllwng parameters: `-Dserver.reverseProxy=true -Dfind.reverse-proxy.pre-authenticatedroles=myDatabases -Dfind.reverse-proxy.pre-authenticated-username=sascuser`

But, You know, FIND search page always lists to me **all databases** active for my searches.
Also, I tried to workaround by putting a string:JsonArray of `"defaultDeselectedDatabases"` in FIND **config.json** but, You know, current user still can **see & activate** any deselected database

IDOL Server: 11.6
o.s.: Windows Server 2012 Standard
FIND 11.6

**Comment by ciroppina** [comment]
I spent some time configuring User and Document Security on my IDOL Server 11.6. Here U are a sample of my settings:

- first I crated a AESKey file and added the corresponding param:
`[Security]`
`SecurityInfoKeys=.\common\AESKeyFile.ky`

- then, In the [UserSecurity] config section I added the following params:
`[UserSecurity]`
`DefaultSecurityType=0`
`SecurityTokenLifetime=24hours`
`0=Autonomy`
`[Autonomy]`
`Library=D:\Program Files\HewlettPackardEnterprise\IDOLServer-11.0.0\community\modules\user_autnsecurity`
`EnableLogging=True`
`DocumentSecurity=TRUE`
`SecurityFieldCSVs=username`

- finally, after restarting IDOL Server (all modules), I was successfully able to obtain a SecurityInfo Token, by issuing:
`http://localhost:19000/a=UserRead&UserName=sascuser&Function=AUTHENTICATE&DeferLogin=false&Password=sascuser&Repository=Autonomy&SecurityAutonomyUsername=sascuser&SecurityInfo=true&SecurityFields=true&UserFieldMatch=*&RoleList=true&Privilege=*`
[or, _short form_:]
`http://95.110.198.219:19000/a=UserRead&UserName=sascuser&Password=sascuser&SecurityInfo=true&Privilege=*`

obtaining the String-Token as the value of `<autn:securityinfo>` tag. Nonetheless, I am already able to search allDatabases in FIND, because user still has  the `databases` **Privilege** as it belongs to the FindUser Role, other than a more restrictive 'myDatabases' Role [which has only four databases access privilege].
What do You suggest to me, for restricting Databases/Documents access now that mapped security is on?
Querying the 'community' 'action=GRL', I can see the **SecurityInfo=true** paramenter; and querying the 'content GRL' I can see the Security Token string is correctly added to the action=Query

I think that FindUser Role privileges overlap my own Role privileges. If I remove my user from role 'FindUser', user cannot login to Find anymore

**Comment by tung-jin-chew-hp** [comment]
Try removing/changing the databases privilege on FindUser so that only your myDatabases role has database privileges?

Also, check that you've set  [Role] AutoSetDatabases=FALSE in your community server's settings; otherwise it'll reset the database permissions each time community starts up.

**Comment by ciroppina** [comment]
Thanks for Suggestions. SOLVED
I removed 'databases' privilege from FindUser and FindBI roles; moreover I removed my "users with restrictions" from 'everyone' role, in that way it's no more necessary to change:

- 	[Role]
	AutoSetDatabases=TRUE 

to FALSE. I solved by creating several roles, each having a 'databases' privilege with a specific list of Idol databases
