### ISSUE TITLE
HOW-TO configure Idol FIND for displaying %-relevance and database-name

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#41]
HOW-TO configure Idol FIND for displaying %-relevance and database-name in the List-of-results?
Is there a 'config-way' ?

![image](https://user-images.githubusercontent.com/15525117/41653623-ea81ba1c-7486-11e8-84c9-90c87f905690.png)

**Comment by tung-jin-chew-hp** [comment]
If you're just using configs; you can configure custom templates to configure the fields, which will work for database name. However, it doesn't currently support % relevance. If you have the Find Admin guide, it'll be in the 'Configure Templates in Find' part of the documentation.

If you're willing to change the code, you can use something like this:
  https://github.com/microfocus-idol/find/commits/example/database-and-weight

which will show the database and the score next to it.

![image](https://user-images.githubusercontent.com/7871081/41655619-4748898a-7485-11e8-8b6a-7da4316fd078.png)

 I'll add the % relevance (aka weight) option to the template renderer for the next release so it won't need custom code in future.
