### ISSUE TITLE
does [a guide about how-to deploy Find into an application server] exist ?

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#42]
Dear Sirs,

I dont know if this is the right place where opening my issue: I need to know if I can deploy "**find.war**" into IBM  WebSphere 9, or another JEE application server

How-to do that?

**Comment by tung-jin-chew-hp** [comment]
Strictly speaking, I don't think it's supported. However, I did get it to work on a different J2EE container (Tomcat 8) by making the small code change on this branch:
  https://github.com/microfocus-idol/find/commits/example/j2ee-container
and deleting the /WEB-INF/lib/tomcat-embed-*.jar files in the built .war file.

See the comments on the commit at
  https://github.com/microfocus-idol/find/commit/f18ac33335cabc433cc530209d0fbbdd7a7d3ca8

**Comment by ciroppina** [comment]
Dear Tung,

I followed these: two
- https://github.com/microfocus-idol/find/commits/example/j2ee-container
- and deleting the /WEB-INF/lib/tomcat-embed-*.jar files in the built .war file

but I guess the tomcat8 deployed find.war is not reading my _config.json_ located at the "idol.find.home"

I have a IDOL Server installed to another computer (**172.28.52.174**) listening to a-little modified http port (_19000, 19010, 19030_, ...) so my current **%JAVA_OPTS%** are as follows:
`set JAVA_OPTS=-Xmx4096m -Didol.find.home=C:/Program%20Files/HPE/idolserver/find/home/ -Dfile.encoding=UTF8 -Didol.log.actionid.enabled=true -Dhp.find.persistentState=INMEMORY -Dhttp.proxyHost=172.28.52.174 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=172.28.52.174 -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=172.28.52.174,localhost,127.0.0.1,192.168.*.* -Dhttps.nonProxyHosts=172.28.52.174,localhost,127.0.0.1,192.168.*.*  -Dserver.port=8081 -Dserver.reverseProxy=true -Dfind.reverse-proxy.pre-authenticatedroles=FindUser,FindBI -Dfind.reverse-proxy.pre-authenticated-username=sascuser
`

Tomcat8 correctly starts Find, but when I try to use it [http://localhost:8080/find] I always get this exception: Cannot connect - because localhost is not listening to port _9030_ : 
`org.apache.http.conn.HttpHostConnectException: Connect to localhost:9030 [localhost/127.0.0.1] failed: Connection refused: connect`

What am I doing wrong?

**Comment by tung-jin-chew-hp** [comment]
Can you check the your C:/Program Files/HPE/idolserver/find/home/config.json ? If you're using a community on 172.28.52.174:19030 then the login section of the config.json should look like this:

    "login" : {
      "name" : "CommunityAuthentication",
      "defaultLogin" : {
        "username" : null,
        "password" : null
      },
      "community" : {
        "protocol" : "HTTP",
        "host" : "172.28.52.174",
        "port" : 19030
      },
      "method" : "autonomy"
    }

You can also change the other hosts and ports listed in that file as well (e.g. the 'content' section to replace localhost with 172.28.52.174 and port 9000 with 19000 etc.)

**Comment by ciroppina** [comment]
SOLVED
My error was to use a `idol.find.home` containing a blank-space (%20)

The final JAVA_OPTS I 'm using is:
`JAVA_OPTS=-Xmx4096m -Didol.find.home=Z:\Programmi\apache-tomcat-8.5.32\find\home -Dfile.encoding=UTF8 -Didol.log.actionid.enabled=true -Dhp.find.persistentState=INMEMORY
`
cause I dont need to proxy Find

NOTICE that I also can add:
`-Dserver.reverseProxy=true -Dfind.reverse-proxy.pre-authenticatedroles=FindUser,FindBI -Dfind.reverse-proxy.pre-authenticated-username=sascuser`

further env-params, to get a pre-authenticated access to Find, and it works!

Finally, I added this config:
`	<Resources cachingAllowed="true" cacheMaxSize="102400" />`
within the &lt;Context&gt; tag of  _tomcat8/conf/context.xml_, in order to avoid thousands cacheing alerts/warnings in tomcat8 _console/server.log_

**Comment by ciroppina** [comment]
Pls, note that the modification to the **IdolConfiguration** class, in the "idol" module, also works for standard Idol Find execution, as a SpringBoot Web App
So, consider to apply and commit such a modification:

- `@ImportResource("classpath:required-statistics.xml")`

**Comment by tung-jin-chew-hp** [comment]
Okay, thanks for the extra notes! I did notice that the @ImportResource change worked in both cases, I'll probably merge the branch back in. I have a few more changes to make to the branch so that the config page will work (so you don't have to manually edit the config file when starting a new setup; didn't notice initially because I'd given it a pre-configured config folder when testing).

**Comment by tung-jin-chew-hp** [comment]
Changes have been merged back into develop; should be in the next release.
