### ISSUE TITLE
search results page: something to show, something to hide

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#43]
Dear Sirs,

is there a guide for changing what is shown in the "List" panel, foreach result?
I woould like to:
- add the % idol relevance (autn:weight)
- add the name of the DREDBNAME (autn:database)
- show more than two rows of text per-result (3 lines would be good)
- hide the ViewServer preview when it contains "500 ViewServer Error" due to the format of the original result, not compatible with browser viewable mime types (see attached image)

![image](https://user-images.githubusercontent.com/15525117/42776190-944b7e0c-8936-11e8-83dc-2fa9cfac4cd2.png)

Also, I finished to translate a good Italian bundle.js - how can I submit it?

**Comment by tung-jin-chew-hp** [comment]
I'm currently away on leave, so this isn't going to be a complete answer, but the example/database-and-weight branch has an example of showing the database and score (aka weight). It requires small code changes which aren't in 12.0 yet, but will be in 12.1.

https://github.com/microfocus-idol/find/tree/example/database-and-weight?files=1

The two-line clamp comes from

.result-summary {
  .text-justify;
  .text-clamp(2, 45px);
}

.result-summary:hover {
  .text-clamp(40, 900px);
}

so you can change 2 to 3 in the LESS files. As from the :hover rule, we show up to 40 lines if you hover over the text. You may have to change the summary character count too (look at the same change which introduced the result-summary:hover LESS rule)

There's an error handler which controls the error response for view errors, so you could change that.

I'm afraid we don't have any Italian speakers on the development team at present, so we wouldn't be able to maintain an Italian translation if we accepted it, sorry. You could perhaps put it on a branch of your own where other Italian speakers could find it though.

Thanks,
Jin

Tung Jin Chew  |  Software Developer, Big Data, Micro Focus  |  tung-jin.chew@microfocus.com
________________________________

**Comment by tung-jin-chew-hp** [comment]
The view controller error handler is here:
  https://github.com/microfocus-idol/find/blob/master/webapp/idol/src/main/java/com/hp/autonomy/frontend/find/idol/view/IdolViewController.java 
see handleViewServerErrorException and handleViewDocumentNotFoundException.

**Comment by tung-jin-chew-hp** [comment]
Welcome; it's the documentSummaryMaxLength option in config.json .

**Comment by ciroppina** [comment]
thanks tung, I ve been able to customize the document viewer with Italian messages
thank You 4 Ue support

I ve 2 more questions but I will open a new issue; this one could be closed
