### ISSUE TITLE
how to hide Find navbar (the small-logo and user menu top area) when accessing search as a pre-authenticated user?

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#45]
Dear Sirs, 

I need to kwow how to completely hide Find navbar (the small-logo and user menu top area) when accessing search as a pre-authenticated user?
Also, as a simpler scenario, wanna know how to make it compltely disappear, at all

I guess it'd be a matter of classes in some .less files...

thanks much

**Comment by tung-jin-chew-hp** [comment]
Easiest way is probably to add the 'hide' class where it currently says 'find-navbar navbar navbar-static-top' in https://github.com/microfocus-idol/find/blob/master/webapp/core/src/main/public/static/js/find/templates/app/navigation.html#L1.

**Comment by ciroppina** [comment]
thanks much Tung, 
closing this issue

**Comment by ciroppina** [comment]
g.m. Tung

I notices, since when I applied 'hide' class to the find-navbar component, that a corresponding (height) white footer appeared to the bottom of the search page, and I am not able to understand how to adjust it (_see the picture_)
Pls, an help from U

![image](https://user-images.githubusercontent.com/15525117/43568311-90913e22-9634-11e8-91f1-10480d5a1b6b.png)

**Comment by ciroppina** [comment]
Sorry,
I SOLVED the footer-height problem simply but setting:
`   @navBarHeight: 0px;`
in:
- core/src/main/resources/less/components/variables-less

this also better than hiding the navbar, by adding class 'hide' to the `navigation.html` template

![image](https://user-images.githubusercontent.com/15525117/43574269-006e0a2c-9644-11e8-8195-a38cfea14b6f.png)

**Comment by tung-jin-chew-hp** [comment]
That's a good point; hadn't noticed the gap. Glad you found a solution.
