### ISSUE TITLE
Lot of problems building just/fresh cloned idol-find 12.0.0

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#46]
Dear Sirs,

since yesterday I am having lot of problems to maven build a fresh git-cloned copy of Idol Find 12.0.0
the maven command I use is, for core module is:
> mvn clean install -DskipTests
for building find,.war, instead, I use:
> mvn clean install -pl core,idol -DskipTests
from within the webapp/ directory

the problem always is that: exec-mave-plugin:1.3.1:exec (npm install) FAILS
in fact, by running a npm install, in the core module directory, it fails! NPM notices me with many Warnings in the loadAllDepsIntoIdealTree phase, concerning how to migrate to Yarn. Then, when trying to validate tough-cookies@2.2.2 I get the following error:
> git ls-remote -h -t https://github.com/jdesrosiers/grunt-peg.git   fatal: unable to connect to github.com [192.30.253.112/113]

I also tried to change git settings, running:
> git config --global url."https://".insteadOf git://
BUT I GOT THE SAME ERROR

I use:
- npm 5.5.1
- java 1.8.0_171
- bower 1.8.4
- on Windows Server 2012 R2 Standard

Could You help me resolving this issue?

many Thxs

**Comment by ciroppina** [comment]
of course, by following Ur Wiki instructions to build find module, by running:
>mvn package -pl <module> -am -Dapplication.buildNumber=$GIT_COMMIT [-DskipTests]

I GOT THE SAME ERROR (MojoExecutionException while _npm install_ phase)

GIT-COMMIT is: a4a221ff7

**Comment by ciroppina** [comment]
Also I noticed that: [parent] com.hp.autonomy.frontend.find:12.0.0 is NOT present on Maven Repo: https://mvnrepository.com

**Comment by tung-jin-chew-hp** [comment]
It's because the github:jdesrosiers/grunt-peg dependency has been moved to github:dvberkel/grunt-peg ; this has been fixed in develop e.g.
  https://github.com/microfocus-idol/find/commit/2bf04aa12fe5c72149f4b925f1bf866d44fe29a6
but master won't be updated till the next release.

**Comment by tung-jin-chew-hp** [comment]
Also, com.hp.autonomy.frontend.find won't be on Maven Repo since it's not an intermediate library, but a completed build. You can get it from the Micro Focus product release downloads page.

**Comment by ciroppina** [comment]
thanks much, Tung,

core module: npm install and maven build now is successful with few modifications:
[npm-shrinkwrap.json]
- "bower": "version": "1.8.4"
- "grunt-peg": "version": "git+https://github.com/dvberkel/grunt-peg.git#7438cc4cba68fe3fd256a8076019d7f3876e2416"
[package.json]
- "grunt-peg": "github:dvberkel/grunt-peg#11252e0"
[pom.xml]
in pegjs execution, added the: <argument>--force</argument>

**Comment by ciroppina** [comment]
idol-find module also now successfully builds and packages the "find.war", by applying few modifications:

[in npm-shrinkwrap.json]
```
    "grunt-peg": {
      "version": "github:dvberkel/grunt-peg#7438cc4cba68fe3fd256a8076019d7f3876e2416",
      "dev": true,
      "requires": {
        "pegjs": "0.9.0"
      },
```

[in package.json]
`    "grunt-peg": "github:dvberkel/grunt-peg",
`

**Comment by ciroppina** [comment]
Also, I had to modify code in:
- webapp/core/node_modules/grunt-peg/tasks/**peg.js**
AFTER having executed the npm install task; in fact pegis@0.10.0 has an error in THAT js file

The correction is to rename a function call: from **PEG.buildParser** to **PEG.generate** 

AFTER such rename, You can remove the argument '--force' in the core module's pom.xml, from the pegjs build task

**Comment by tung-jin-chew-hp** [comment]
Just for reference for anyone trying to build 11.6, you'll need to cherry pick in the 2bf04aa12fe5c72149f4b925f1bf866d44fe29a6 grunt-peg dependency change and the 2b7558d194a2246e7cf5f70b35a788b9fdcda281 bower change from develop for it to build, e.g.

    git clone git@github.com:microfocus-idol/find.git -b onprem-release/11.6.0
    cd find
    git cherry-pick 2bf04aa12fe5c72149f4b925f1bf866d44fe29a6
    git cherry-pick 2b7558d194a2246e7cf5f70b35a788b9fdcda281
    cd webapp
    mvn clean package -pl idol -am -DskipTests=true -Pproduction

since bower versions and grunt-peg have changed since that release was published.
