### ISSUE TITLE
FindBI role (looks like) not working with Find 12.0.0

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#48]
Dear Sirs,
looks like the FindBI Idol role is no more working in Find **12.0.0**

see the attached image
![findbi_not_working](https://user-images.githubusercontent.com/15525117/43475696-d40e7514-94f6-11e8-9279-d5058b06a7b8.png)

Also I attach my (unchanged, since Find 11.6) config.json
[config.json.zip](https://github.com/microfocus-idol/find/files/2246404/config.json.zip)

My launching command is as follows:
`java -Dserver.reverseProxy=true -Dfind.reverse-proxy.pre-authenticatedroles=FindUser,FindBI -Dfind.reverse-proxy.pre-authenticated-username=sascuser -Didol.find.home=.\home -Dserver.port=15080 -jar find.war_12.0`

where 'sascuser' is a mamber of both FindBI and FindUser roles
I do not see some familiar UI items anymore, such as:
- a text input field for filtering database and parametric fileds names
- SAVE and SAVE SNAPSHOT buttons
- Share Saved Searches link
- and so on...

**Comment by tung-jin-chew-hp** [comment]
All the UI options you mention are controlled by the presence of the FindBI role on the user. It's because you have a typo, there's a missing '-' between 'authenticated' and 'roles' in your

    -Dfind.reverse-proxy.pre-authenticated-roles=FindUser,FindBI

**Comment by tung-jin-chew-hp** [comment]
If you stop the existing server, add the missing '-' to the your launch command and run it again it should work.

**Comment by ciroppina** [comment]
You are right, 
closing...
