### ISSUE TITLE
filtering search results' list by means of an external system

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#49]
Dear Sirs,

Let me describe my development scenario:

a) I already was able to create a custom template, appliable by its triggers on the query results' list, for showing my Idol custom field content in the 'black badge', see this picture:
![image](https://user-images.githubusercontent.com/15525117/43629998-3e313706-96ff-11e8-8cd4-c1cdf80231db.png)

b) custom template currently applies ONLY to results coming from a couple of _indexes_ (_Idol databases_) that have the custom field whose content I need to show in the badge. But I need to implement a further filtering rule to be applied to results. I need to show the 'black badge' ONLY if the current user in NOT-AUTHORIZED to read a result in the list. Such authorization concerns permissions the current user has to access the "Fascicolo" (that's my Idol custom field) and such an auth is not managed by Idol (ACL, SecurityInfo) but it is managed by an external system, a REST-API JEE application that exposes some JPA-Repo endpoints to check for current user permissions. Permissions are stored to a SQLServer DB-schema

c) is there a way to modify Find Java code in order to query the external system, AFTER the Idol-query action, for current user's authorized list of "Fascicolo"?

_NOTICE: "Fascicolo" is the italian for "Folder", a collection of documents, held by an Alfresco ECM instance, but that complexity is all-managed behind the system that exposes permissions endpoints_

**Comment by tung-jin-chew-hp** [comment]
If the idea is to hide documents which the user is not allowed to see; I would recommend using IDOL's document-level mapped security instead; which can selectively hide or show documents based on the user's permissions in content itself; rather than trying to filter in Find itself.

See https://www.microfocus.com/documentation/idol/IDOL_12_0/IDOLServer/Guides/pdf/English/IDOL_12.0_DocumentSecurity_en.pdf

**Comment by ciroppina** [comment]
I already used IDOL DOCUMENT MAPPED SECURITY in prevs projects, mapping LDAP Users and Groups to Idol by using OmniGroupServer and providing ACL when importing documenta to Idol indexes. Also using SecirityInfo tokens with every query. And it works!
But I fear I cannot in this current scenario:
- customer is a main domestic security agency and they do not want/can map part of their internal LDAP domain (Groups, Users) to Idol; it is a legal impediment
- document's permissions vary very frequently, even more than once per-day, so keeping documents ACLs updated being very demanding
- finally, Idol Find should interact with another system, exchanging some data (in the request/response headers) such as: user-identity, portal-identity, resulting not-allowed "Fascicolo"-IDs; i.e. user should be able to click the black-badge and so sending the "Fascicolo"-ID, readable in the badge, to the other system (another web application) in order to issue a "request for temporary access/search authorization"

**Comment by tung-jin-chew-hp** [comment]
Well, if you really want to, you can try adding code to the end of com.hp.autonomy.types.requests.Documents#query to call out to your external server and censor the results.
  https://github.com/microfocus-idol/find/blob/9cffadd8d7a6182fe72a68be667e742c917b258c/webapp/idol/src/main/java/com/hp/autonomy/frontend/find/idol/search/IdolDocumentsController.java#L153

I don't think this is a good idea though; since the original text may still be leaked in query summaries or other aggregate information.

**Comment by tung-jin-chew-hp** [comment]
Sorry, correction; that's actually the "recommend-documents" callback; forgot to rename it. 

If you're doing the censoring; you actually want to add a new method to that same file to override the query method on the superclass, e.g.

    @Override
    public Documents<IdolSearchResult> query(
            @RequestParam(TEXT_PARAM) final String queryText,
            @RequestParam(value = RESULTS_START_PARAM, defaultValue = "1") final int resultsStart,
            @RequestParam(MAX_RESULTS_PARAM) final int maxResults,
            @RequestParam(SUMMARY_PARAM) final String summary,
            @RequestParam(value = INDEXES_PARAM, required = false) final List<String> databases,
            @RequestParam(value = FIELD_TEXT_PARAM, defaultValue = "") final String fieldText,
            @RequestParam(value = SORT_PARAM, required = false) final String sort,
            @RequestParam(value = MIN_DATE_PARAM, required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) final ZonedDateTime minDate,
            @RequestParam(value = MAX_DATE_PARAM, required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) final ZonedDateTime maxDate,
            @RequestParam(value = HIGHLIGHT_PARAM, defaultValue = "true") final boolean highlight,
            @RequestParam(value = MIN_SCORE_PARAM, defaultValue = "0") final int minScore,
            @RequestParam(value = AUTO_CORRECT_PARAM, defaultValue = "true") final boolean autoCorrect,
            @RequestParam(value = INTENT_BASED_RANKING_PARAM, defaultValue = "false") final boolean intentBasedRanking,
            @RequestParam(value = QUERY_TYPE_PARAM, defaultValue = "MODIFIED") final String queryType
    ) throws AciErrorException {
        final Documents<IdolSearchResult> results = super.query(queryText, resultsStart, maxResults, summary, databases, fieldText, sort, minDate, maxDate, highlight, minScore, autoCorrect, intentBasedRanking, queryType);

        final List<IdolSearchResult> origDocs = new ArrayList<>(results.getDocuments());

        results.getDocuments().clear();

        for(final IdolSearchResult doc : origDocs) {
            final String username = authenticationInformationRetriever.getPrincipal().getName();
            // TODO: call some external server based on the username
            final boolean redact = true;

            if (redact) {
                // we are arbitrarily hiding the summary, and saying 'redacted' instead
                results.getDocuments().add(doc.toBuilder()
                    .summary("redacted")
                    .build());
            }
            else {
                results.getDocuments().add(doc);
            }
        }

        return results;
    }

The same information-leaking-via-query-summaries-or-other-aggregate-information considerations apply though; so it's not really a good idea.

**Comment by ciroppina** [comment]
I am trying to implement it.

I want to call "Idol Find" url (from another application) passing some Request Params, this way:
   `http://localhost:15080/public/search/query?basicToken=[aBase64Token]&idPortaleRis=3`
_(note: launching Idol Find webapp as a pre-authenticated service)_

Then, in my Override of the "recommend-documents" callback, I want to be able to read such two params, something like this:

```
   // how to get these two ?
   final int **idPortaleRis** = requestParamsRetriever.getIdPortale()
   final String **basicToken** = "Basic " + requestParamsRetriever.getBasicToken();
   
   for(final IdolSearchResult doc : origDocs) {
	// final String username = authenticationInformationRetriever.getPrincipal().getName();
	// TODO: call some external server based on the username
      
       // call to external endpoint - here
   }
```
cause I need them for calling the external-system endpoint. 
Could you let me know the way to pass those two-params throughout up to my overridden method, in the "**IdolDocumentsController.java**" class ?

**Comment by ciroppina** [comment]
thank You Tung, v.m.,

inspecting the ["idol" module] query Controller class (_IdolDocumentsController.java_) I am not able to find a parameter corresponding to the 'famous' **_anyLanguage_** boolean param for the Idol query action. How to add it?
I need query returns results in more than 1 language, at least Italian and English

**Comment by ciroppina** [comment]
Sorry Tung,

by using the new method/code U suggested to me:
"_If you're doing the censoring; you actually want to add a new method to that same file to override the query method on the superclass, e.g. ..._"

I am experiencing an error in visualizing the results List: _Required String parameter 'text' is not present_
and I see:

![image](https://user-images.githubusercontent.com/15525117/43888123-024fbb74-9bc1-11e8-8af2-58649fc926b8.png)

I tried to provide the queryText param to the URL:
- localhost:15080/public/search/query?queryText=omicidio
or
- localhost:15080/public/search/query?text=omicidio
but the error still happens

Also, I tried to use some null/empty guard-clauses in the method body:
```
//guard-clauses
String theQueryText=queryText, theSummary=summary; int theMaxResults=maxResults;
if (theQueryText == null || theQueryText.isEmpty() ) theQueryText="*";
if (theMaxResults < 1) theMaxResults=30;
if (theSummary == null || theSummary.isEmpty() ) theSummary="";
		
final Documents<IdolSearchResult> results = super.query(
	theQueryText, resultsStart, theMaxResults, theSummary, databases, fieldText, 
		sort, minDate, maxDate, highlight, minScore, autoCorrect, intentBasedRanking, queryType);
```

but it still happens. I cannot understand what is the origin of that error. In the browser console I have:

![image](https://user-images.githubusercontent.com/15525117/43888391-d9f66ae6-9bc1-11e8-8f92-5eee5c1c68e7.png)

**Comment by tung-jin-chew-hp** [comment]
The anylanguage=true parameter is already being sent; look at the action=grl of IDOL or the content engine query logs to confirm that. 
If you're searching with terms which should return results in English and Italian and you're only getting English; your content engine language settings are probably not configured correctly; talk to Micro Focus support for advice. 

Without seeing your configs and data it's impossible to diagnose; but possibly the solution would involve adding
   ` [LanguageTypes] GenericStemming=true`
to your content config; and if you have `[english] NgramMultiByteOnly=TRUE` replace it with `[english] NGramOrientalOnly=true` . After making changes, you'd have to reindex the content (DREEXPORTIDX/DREEXPORTXML your data to save it, DREINITIAL to wipe all data and use new config, DREIMPORT your idx/xml back in).


As for your `Required String parameter 'text' is not present` error, I can't debug it without having your code and stack traces since you've made your own changes. https://github.com/microfocus-idol/find/tree/example/scoped-bean-parameter-passing builds correctly for me. Try running `mvn clean` to remove all existing built files, then build again and see if that helps.

**Comment by ciroppina** [comment]
### **_It works!_**
my error was to leave the 'original_12.0.0' _query_ method un-renamed; I followed Your #49-issue code-sample and now I have no more ('text' param) errors. Moreover, I can receive the two passed request-params through autowiring Ur _Holder_ Component both into _IdolDocumentsController_ and _IdolFindController_ classes, of the "idol" module

I think we can close this issue, now.
If I need more help, I will open it again

**Comment by ciroppina** [comment]
dear Tung Jin Chew

I dont want to repoern this issue, but I have a question:
see my attache image on "Apr 3rd": I added to the results List a black badge as a background for my custom data ("... Protocollo ASC-..."). Such a badge has its onclick method (it copies the Protocollo_ID to the browser clipboard) BUT when I click it also the results List standard behavior happens, details open to the right side of the List. How could I avoid to open details panel ONLY for those results with the custom-data black badge ? (only in such cases I dont want details to be shown)

Many Thanks, b.r.

**Comment by ciroppina** [comment]
it worked perfectly!

many thanks
