### ISSUE TITLE
custom handlebars templates - how to condition style attributes

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#51]
Dear Sirs,

I developed a custom handlebars template for some custom IDOL DREfields. The trigger is: if those fields are present in a returned Idol result, the template is applied to such a result, in the List Panel

Now I need to implement a further condition, of CSS-style fashion: if the {{summary}} field contains the string "NON-AUTORIZZATO" the **color** of the Summary must be '**darkred**', if not it must be '**#a2a2a2**'

So, I added in my template a <div> with the following ternary-conditioning in the style attribute value:
```
<div class="document-database m-t-xs m-l-xs" 
   style="{{ (summary.indexOf('NON-AUTORIZZATO') != -1) ? 'color:darkred;' : 'color:#a2a2a2;' }}">
      {{summary}}
</div>
```

but it does not work. It gives an angular syntax error, in the browser console: unespcted symbol (at the beginning of the style value)
NOTICE: all the remnant template code, both html, angular and handlears works well!
I attach it here

[sasc.handlebars.txt](https://github.com/microfocus-idol/find/files/2333341/sasc.handlebars.txt)

**Comment by tung-jin-chew-hp** [comment]
It's a handlebars template, not arbitrary javascript code. You should use the #equal helper instead, something like

`
    {{#equal summary 'NON-AUTORIZZATO'}}
            something
    {{else}}
            something else
    {{/equal}}
`

**Comment by tung-jin-chew-hp** [comment]
The Find Admin guide on https://www.microfocus.com/documentation/idol/IDOL_12_0/Find_12.0_Documentation.zip has a list of all the available helpers.

**Comment by ciroppina** [comment]
I am trying the 'regeIf' helper, according to Find 12 pdf Guide. (I need to check _contains_, not _equal_)
But I always get this error:
"Missing helper: "regexIf" "

my code being as follows:

```
{{#regexIf 'NON-AUTORIZZATO' summary i }}
	<div class="document-database m-t-xs m-l-xs" style="color: darkred !important;">
		{{summary}}
	</div>
{{else}}
	<div class="document-database m-t-xs m-l-xs">
		{{summary}}
	</div>
{{/regexIf}}
```

where the '**i**' param is a flag that means case-insensitive. What is wrong ?
NOTICE: documentation lacks to evidence if the **regexIf** accepts a _{{else}}_ branch

**Comment by ciroppina** [comment]
Also I tried another built-in helper **hasFieldValue**:

```
{{#hasFieldValue summary "NON-AUTORIZZATO" }}
	<div class="document-database m-t-xs m-l-xs" style="color: darkred !important;">
		{{summary}}
	</div>
{{else}}
	<div class="document-database m-t-xs m-l-xs">
		{{summary}}
	</div>
{{/hasFieldValue}}
```
It gives me no errors, but it does not work as a string.contains. The block is always **false**

**Comment by tung-jin-chew-hp** [comment]
Are you actually using 12.0, or an earlier version of Find? regexIf is a relatively new addition, only added for 12.0.

________________________________

**Comment by ciroppina** [comment]
12.0 of course


Il gio 30 ago 2018 21:02 tung-jin-chew-hp <notifications@github.com> ha
scritto:

**Comment by tung-jin-chew-hp** [comment]
hasFieldValue 'contains' is array contains, not string contains. Basically a field can take multiple values, not just one; the test will pass if any one of those values is an exact match for the string to test. 

This is the syntax for regexIf
    {{#regexIf '\d+' title }}
        <div>title contains a number</div>
    {{else}}
        <div>title does not contain a number</div>
    {{/regexIf}}

https://github.com/microfocus-idol/find/blob/cdb8fb57039091f95fe530005fa64198ceb1f83f/webapp/core/src/main/public/static/js/find/app/page/search/document-renderer.js#L137 defines the regexIf helper. Are you using the standard 12.0 release, or your own customized version of it?

**Comment by tung-jin-chew-hp** [comment]
(also in your example, the 'i' flag should be in quotes)

**Comment by ciroppina** [comment]
Tung, 
thank you v.m.
I already used #regexIf without success, because: the problem was the last U mentioned: flags='i' !!!
Now the conditional block works well

We can close this issue
