### ISSUE TITLE
how to pretty-print databases and parametric fields names, in Find left sidebar

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#52]
Dear Sirs,

I need to print more-friendly names in the left panel of Find.
As You see in the attached image, I have a standard prefix for some of my database names, and parametric fields names: "SASC_"
I don want to change all those names by removing "SASC_" in my idolserver.cfg, nor in the IDOL indexes (i.e., I dont want to re-index all the content after a lot of db names and parmetric names modifications)

Is there a way to map Idol names with more-pretty names, i.o. to be visualized in Find Left Panel?
I 'd like to be able to show, for example:
"RSS", for SASC_RSS
"DB", for SASC_DB
"CATEGORIA", for SASC_CATEGORIA
... and so on

![image](https://user-images.githubusercontent.com/15525117/45889118-ebf67180-bdbf-11e8-82cb-ee1c84fdc733.png)

**Comment by tung-jin-chew-hp** [comment]
Parametric field names can be easily relabelled in the UI in the config.json fieldsInfo section, by declaring field for each of your parametric fields with a displayName, e.g.

    "fileType" : {
      "advanced" : true,
      "names" : [ "IMPORTMAGICEXTENSION" ],
      "displayName" : "File Type",
      "values" : [ ]
    },

where 'IMPORTMAGICEXTENSION' is the IDOL field name, 'File Type' will be the label shown in the UI, and 'fileType' is the Find field name used to reference the field in custom templates etc.

You can easily change your IDOL database names with the 'DRERENAMEDBASE' action, without having to reindex anything.

**Comment by ciroppina** [comment]
many thanks, Tung
it works! I close this issue
