### ISSUE TITLE
how to add a new panel to the central "resultView"

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#53]
Dear Sirs

I current received e request:
- to add another **custom** panel to the resultView (after List, TopicMap, Sunburst, ...)
- such a panel will contain a **custom** request form and its list of filtered results 

Is there a not-so-complex way to do it? 

![image](https://user-images.githubusercontent.com/15525117/46249479-154f7700-c42a-11e8-8d0e-5b881c4bb93d.png)

**Comment by tung-jin-chew-hp** [comment]
That is probably out of the scope of an issue ticket. You'd have to modify the code, e.g. adding a new tab to webapp/core/src/main/public/static/js/find/app/page/search/service-view.js ; and make it visible in the webapp/idol/src/main/resources/defaultIdolConfigFile.json .

See 20142f35c06a7dd3b36ad360bd7edcbabb821e91 and cdd59fa495412e2d9e1f559bf49aa720b9ba4fa7 for an example of how a new tab was last added.
