### ISSUE TITLE
Not compiling due to changes in dependencies repos

### ISSUE THREAD

**Issue by Yuntaz** [microfocus-idol/find#54]
Two mayor issues detected and fixed:

1) Please, The repo: github:jdesrosiers/grunt-peg has been deleted. Need to use github:dvberkel/grunt-peg. Otherwise will give an error during building

2) Please, Change https://bower.herokuapp.com/ because is down. Need to point to https://registry.bower.io

Thanks

**Comment by tung-jin-chew-hp** [comment]
Thanks for the report! It's actually fixed on the develop branch already; please refer to the develop branch when building your own code since the master branch is only updated on each official release.
