### ISSUE TITLE
how to configure "OutputType=HTML" in the "View" section of config.json

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#56]
Dear Sirs

Document Preview, in Find, always fails (HTTP-Code 500) for most of indexed documents that are not html, neither have public urls.
In my installation docs' DREREFERENCEs points to local web server and docs' formats are: txt, doc, docx, xls, pdf, odt, ods, and so on; Find Document Preview is not able to show their Preview. 
I suspect that the calls to the Idol View Server have not the **OutputType** parameter set to "**html**" (it would convert every doc-format into html)

I checked in the "home/config.json" file and in the Help ("**_Find_12.0_Administration_en.pdf_**") but I cannot find any description of the "view" section, if the "OutputType" param could be added there:

[currently I have the following]:
```
  "view" : {
    "connector" : {
      "protocol" : "HTTP",
      "host" : "95.110.198.219",
      "port" : 10000
    },
    "referenceField" : "DREREFERENCE",
    "viewingMode" : "FIELD",
    "highlighting" : true,
    "host" : "95.110.198.219",
    "protocol" : "HTTP",
    "port" : 19080
  },
```

**Comment by ciroppina** [comment]
Error example
the following image shows Find unable to Preview an outer html page, from an external RSS site:

![image](https://user-images.githubusercontent.com/15525117/46603481-77c40980-caf3-11e8-9183-7a4ef46a101e.png)

the usr is:
- [https://www.repubblica.it/cronaca/2018/06/14/news/diete_truffa_ordine_medici_denuncia_alla_procura_adriano_panzironi-199004441/?rss](https://www.repubblica.it/cronaca/2018/06/14/news/diete_truffa_ordine_medici_denuncia_alla_procura_adriano_panzironi-199004441/?rss)

**Comment by tung-jin-chew-hp** [comment]
This isn't a Find question, it's a view server question; you should check the admin guides or contact support if you're running into problems.

At a guess, it might be you're missing the SSL config section 

    [Viewing]
      …
    OutgoingSSLConfig=SSLSection
      …

    [SSLSection]
    SSLMethod=SSLV23 

or the proxy settings (change them to point at your own proxy server)

     [Viewing]
      …
     ProxyHost=web-proxy.sdc.hpecorp.net
     ProxyPort=8080
     NoProxyHostsCSVs=localhost
      …
