### ISSUE TITLE
Dependency GRUNT-PEG is unavailable

### ISSUE THREAD

**Issue by guileh** [microfocus-idol/find#57]
This dependency "grunt-peg": "github:jdesrosiers/grunt-peg#11252e0" fails building the application.
===========================
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/jdesrosiers/grunt-peg.git
npm ERR!
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/jdesrosiers/grunt-peg.git/'
npm ERR!
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
============================

**Comment by catmanjan** [comment]
I changed the grunt-peg dependency to refer to the npm package instead of the github and it appears to have worked
