### ISSUE TITLE
moving "CORRELATED" sidebar from right to left

### ISSUE THREAD

**Issue by ciroppina** [microfocus-idol/find#59]
Dear Sirs,

is it possible to customize Find layout so that the "CORRELATED" panel on the right  could be moved to the left, **between** the filter sidebar and the results/statistics tabs ?

Also, I would like to change the (...) circle button (the one that drops two items: export, delete) into two separate horizontal buttons "Export to CVS" and "Delete Query" 

thankYou v.m.

ciroBorrelli

**Comment by ciroppina** [comment]
no replies since 1 month?

**Comment by ciroppina** [comment]
dear Sirs,

I am going to restart my customization tasks on Idol Find app, in few days - but You did not reply to my issies since Nov 2018

**Comment by tung-jin-chew-hp** [comment]
You can move the 'right-side-container' div to be before the 'middle-container' in webapp/core/src/main/public/static/js/find/templates/app/page/search/service-view.html to change the order.
![image](https://user-images.githubusercontent.com/7871081/51984754-fd4d3a00-2493-11e9-8a10-816db8ef1f3b.png)

You can change the dropdown menu for buttons on webapp/core/src/main/public/static/js/find/templates/app/page/search/saved-searches/saved-search-control-view.html

The Github issue tracker is meant to be used for reporting bugs, not for requests for help with customization.

**Comment by ciroppina** [comment]
Many thanks dear Yung-Jin Chew

Since my company (Perfexia Srl, Italy) is a commercial and technical
partner of Microfocus, for Idol platform, which is the 'channel' I should
use to ask for help with Find customization?

Thank You, best regards

ciroBorrelli
___



Il giorno mer 30 gen 2019 alle ore 14:39 tung-jin-chew-hp <
notifications@github.com> ha scritto:
