### ISSUE TITLE
"Building Find" instructions do not work due to missing git package

### ISSUE THREAD

**Issue by catmanjan** [microfocus-idol/find#60]
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t https://github.com/jdesrosiers/grunt-peg.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/jdesrosiers/grunt-peg.git/' not found
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sysadmin.INTERNAL\AppData\Roaming\npm-cache\_logs\2018-11-08T23_44_41_556Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for find 12.0.0:
[INFO]
[INFO] find ............................................... SUCCESS [  2.141 s]
[INFO] core ............................................... FAILURE [05:27 min]
[INFO] idol ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:39 min
[INFO] Finished at: 2018-11-08T23:44:41Z
[INFO] ------------------------------------------------------------------------

**Comment by catmanjan** [comment]
Replacing jdesrosiers with dvberkel in find/webapp/core/npm-shrinkwrap.json seems to resolve this - I think the github link should be replaced with something more authoritative though!

**Comment by catmanjan** [comment]
I changed the grunt-peg dependency to refer to the npm package instead of the github and it appears to have worked

**Comment by catmanjan** [comment]
duplicate of #57

**Comment by chris-blanks-mf** [comment]
Thanks @catmanjan.  The steps I took to do this:

1. Deleted `core/npm-lockfile.json`
1. Edited `core/package.json` as follows:
    ```diff
    - "grunt-peg": "github:jdesrosiers/grunt-peg#11252e0",
    + "grunt-peg": "2.0.1",
    ```
1. re-ran maven build

After building, npm will have created a new `core/package-lock.json` file.  If you want to convert this to a lock file, run:

```bsh
$ cd core
$ npm shrinkwrap
npm notice package-lock.json has been renamed to npm-shrinkwrap.json. npm-shrinkwrap.json will be used for future installations.
```
